# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.43.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: verifyPlugin
        name: verifyPlugin
        entry: ./gradlew verifyPlugin
        language: system
        stages: [pre-push]
        pass_filenames: false
      - id: test
        name: test
        entry: ./gradlew test -x detekt
        language: system
        stages: [pre-push]
        pass_filenames: false

